### ISSUE TITLE
qemu edu device and buildroot qemu

### ISSUE THREAD

**Issue by cirosantilli** [levex/kernel-qemu-pci#2]
Just to let you know: since you've written this great example, the following happened:

- the `edu` educational PCI device was added to the QEMU tree
- Buildroot also builds QEMU from source, allowing you to control version and patch QEMU easily without copying the full source :-)

Here is an example kernel module for it: https://github.com/cirosantilli/linux-kernel-module-cheat/blob/701230021d0a93169f348bf9ec3ef8bc1c2c8c3c/kernel_module/pci.c

Also, next time you are looking for an internship / job, have a look at: https://www.arm.com/careers/index.html , I have a feeling you may like the place.

**Comment by levex** [comment]
Thanks @cirosantilli! I will rewrite this coming next week to reflect your comments.

**Comment by cirosantilli** [comment]
If you do that, I recommend forking my repo :-)

But at this stage, I don't know if there is much point anymore, since edu is already in-tree ;-)

What I think is missing however, is a non-pci example that deals with in / out instruction, does memory IO and generates interrupts. Or an USB example!
